name = "cloudnest-idc"
compatibility_date = "2026-07-28"

[env.production]
vars = { ENVIRONMENT = "production" }

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[build]
command = "cd frontend && npm run build"
publish = "dist"
